version: '3.7'

networks:
  hydranet:
    name: "hydranet"

services:
  hydra-migrate:
    depends_on:
      auth-db:
        condition: service_healthy
    container_name: hydra-migrate
    image: oryd/hydra:latest
    environment:
      - DSN=postgres://auth:secret@auth-db:5432/auth?sslmode=disable&max_conns=20&max_idle_conns=4
    command: migrate sql -e --yes
    networks:
      - "hydranet"

  hydra:
    container_name: hydra
    image: oryd/hydra:latest
    depends_on:
      - auth-db
      - hydra-migrate
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command:
      serve -c /etc/hydra/config/hydra.yml all --dev
    restart: on-failure
    networks:
      - "hydranet"
    volumes:
      - type: bind
        source: ./config
        target: /etc/hydra/config

  auth-db:
    image: postgres:alpine
    container_name: auth-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=auth
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - "hydranet"

  #consent-app:
    #container_name: consent-app
    #environment:
      #- HYDRA_ADMIN_URL=http://hydra:4445
    #build:
      #context: ./consent-app/
      #dockerfile: Dockerfile
    #depends_on:
      #- hydra
    #volumes:
      #- ./consent-app:/consent-app
      #- '/consent-app/node_modules'
    #ports:
      #- "3000:3000"
    #env_file: ./consent-app/consent-app.env
    #networks:
      #- "hydranet"
  #consent:
    #environment:
      #- HYDRA_ADMIN_URL=http://hydra:4445
    #image: oryd/hydra-login-consent-node:v2.2.0
    #ports:
      #- "3000:3000"
    #restart: unless-stopped
    #networks:
      #- intranet