version: '3'

services:
  hydra:
    container_name: hydra
    command: 'tail -f /dev/null'
    build:
      context: ./oauth-server/
      dockerfile: Dockerfile
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
    env_file: ./oauth-server/oauth-server.env
    volumes:
      - ./oauth-server/hydra-entrypoint.sh:/hydra-entrypoint.sh
    #entrypoint: ["/bin/bash", "/hydra-entrypoint.sh"]
    depends_on:
      postgresd:
        condition: service_healthy

  postgresd:
    container_name: postgresd
    image: postgres
    env_file: ./postgresd/postgresd.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgresd/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hydra"]
      interval: 10s
      timeout: 5s
      retries: 5

  consent-app:
    container_name: consent-app
    build:
      context: ./consent-app/
      dockerfile: Dockerfile
    volumes:
      - ./consent-app:/consent-app
      - '/consent-app/node_modules'
    ports:
      - "3000:3000"
    env_file: ./consent-app/consent-app.env
